ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY install.sh /tmp/
RUN /tmp/install.sh

ENTRYPOINT [ "pzmod" ]
